### ISSUE TITLE
Add a telegram bot that returns the student's class schedules

### ISSUE THREAD

**Issue by eyobofficial** [eyobofficial/Gebeya-Schedule-Bot#1]
# Summary
Initialize a telegram bot that receives a message from a user and registers him/her.

## Tasks
- [x] Add a new Django app called `bot`.
- [x] When a user sends a message to the bot, register the user and sends back a welcome message. 
- [x] Depending on the user's command, return the user's class schedule for `today`, `tomorrow`, `this week` and `this month`.

**Comment by KidusMT** [comment]
This is a nice app to work on. I might be the first user. Any help, let me know. Regards.

**Comment by eyobofficial** [comment]
Thank you. I will definitely need help as the development of the bot
progress. I will let you know then.

Have a wonderful day!
