### ISSUE TITLE
Move the database from SQLite to MYSQL

### ISSUE THREAD

**Issue by eyobofficial** [eyobofficial/Gebeya-Schedule-Bot#18]
# Summary
Currently, the default database used by the application is `SQLite3`. Change the database to the more robust `MYSQL`. While doing so, take special care for the handling of date comparisons as Django's ORM [doesn't handle that](https://docs.djangoproject.com/en/2.2/ref/models/querysets/#datetimes) when used with 'MYSQL`.

## Tasks
- [ ] Using Django fixtures, move the data to JSON (or YAML) files for later use.
- [ ] Replace the database settings to use `MYSQL` database.
- [ ] Load the time zone tables with [mysql_tzinfo_to_sql](https://dev.mysql.com/doc/refman/8.0/en/mysql-tzinfo-to-sql.html) to support date comparsion.
- [ ] Run the fixture files to restore the previous data.
